# MailGun properties
mailgun.api.domain: sandbox0dd1452134574239b79c2dba690cc680.mailgun.org
mailgun.api.messages.url: https://api.mailgun.net/v3/sandbox0dd1452134574239b79c2dba690cc680.mailgun.org/messages
mailgun.api.username: api
mailgun.api.password: ${MAILGUN_API_PASSWORD}

# SendGrid properties
sendgrid.api.key: ${SENDGRID_API_KEY}
sendgrid.api.url: https://api.sendgrid.com/v3/mail/send

---
# For aws environment deployment
spring:
    profiles: cloud
    application:
        name: mail-service
server:
  port: 9080

---
# For local environment deployment   

spring:
    profiles: local
    application:
        name: mail-service

server:
  port: 9080
